# Generated by Django 4.0.5 on 2022-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_employee_delete_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('', '-----'), ('female', 'Female'), ('male', 'Male')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
